name: 'Setup K6 Performance Testing'

description: 'Downloads and installs k6 at the specified version and configures OS with k6 optimized settings for stress testing.'

inputs:
  version:
    description: 'The version of k6 to install.  Do not include the `v` in the prefix.  At this time only versions 0.32.0 and higher will work with this action.'
    required: true
  architecture:
    description: 'Target operating system architecture for K6 to use. Examples: arm64, amd64. Will use system architecture by default.'
    required: false
    default: 'amd64'
  extension-download-url:
    description: 'Url for custom k6 binary to download.'
    default: 'none'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Download K6'
      shell: bash
      working-directory: '${{ github.action_path }}'
      env:
        VERSION: ${{ inputs.version }}
        ARCH: ${{ inputs.architecture }}
        EXTENSION_DOWNLOAD_URL: ${{ inputs.extension-download-url }}
      run: |
        node ./dist/index.js
    - name: Tune OS
      shell: bash
      run: |
        echo "Optimizing OS for Stress Test"
        sudo cp -fr /etc/security/limits.conf /etc/security/limits.conf.bk
        sudo sed -i "s/65536/1048576/" /etc/security/limits.conf
        sudo sysctl -w net.ipv4.tcp_tw_reuse=1
        sudo sysctl -w net.ipv4.ip_local_port_range="16384 65000"
        sudo sysctl -w fs.file-max=1048576
        sudo sysctl -p

        echo "Updated open file limit setting, reuse TCP port setting, and port range setting below:"
        sudo sysctl -a | grep -E 'net.ipv4.ip_local_port_range|net.ipv4.tcp_tw_reuse|fs.file-max'
